### ISSUE TITLE
你们是否知道有一个基于巴蜀 OJ 而魔改的 CWOJ？

### ISSUE THREAD

**Issue by t123yh** [z4yx/bashu-onlinejudge#12]
https://cwoj.org
https://github.com/CDFLS/CWOJ
https://github.com/CDFLS/cwoj_daemon
感谢你们！

**Comment by z11g** [comment]
并不知道，不过我觉得挺好的，开源意义就在于此：）

**Comment by t123yh** [comment]
Forgive my naiveness.
