### ISSUE TITLE
mysql_real_escape_string存在安全隐患

### ISSUE THREAD

**Issue by xsaddata** [z4yx/bashu-onlinejudge#15]
ajax_profile里面更新的时候用的是mysql_real_escape_string，这个转义可以用utf宽字符来绕过从而导致sql注入漏洞。

**Comment by xsaddata** [comment]
好多处都使用不安全的mysql_real_escape_string来防止注入，好像搜索也是

**Comment by z4yx** [comment]
啊，是当时不小心用了一些落后的技术，应该换成用placeholder的方式而不是拼字符串。但是现在没有动力大改了[捂脸]。不知道有没有什么简单的fix。

**Comment by xsaddata** [comment]
哈哈，偷懒的方法：
1，用OWASP提高到ESAPI.encoder().encodeForSQL()全部安全转码，进一步偷懒干脆在文件里面重载一下mysql_real_escape_string
2，使用pdo等等预编译
额还有一些吧，另外看message的php可要加一下是否登录的验证哦，不然写个爬虫就把小秘密都扒下来了。

**Comment by z4yx** [comment]
好，我看下怎么改。
你看得真仔细，message那个都被你发现了，当时其实是为了google custom search留的“后门”。

**Comment by z4yx** [comment]
你能找到mysql_real_escape_string不安全的实例吗，我查了下没有找到实际存在的攻击例子。

**Comment by xsaddata** [comment]
抱歉没有看到设置了字符集是UTF-8，大致不用担心了。但是这个方法在新版本的php中已经废除。

http://php.net/manual/en/function.mysql-real-escape-string.php

https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string
