### ISSUE TITLE
Web配置失败

### ISSUE THREAD

**Issue by xslingcn** [z4yx/bashu-onlinejudge#18]
使用LAMP环境，Web无法访问

> 该网页无法正常运作 127.0.0.1 目前无法处理此请求。
HTTP ERROR 500

**Comment by xslingcn** [comment]
查阅错误信息：

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/code/inc/database.php:2 Stack trace: #0 /var/www/html/code/index.php(11): require() #1 {main} thrown in /var/www/html/code/inc/database.php on line 2

**Comment by xslingcn** [comment]
环境：PHP 7.0.32-2+ubuntu16.04.1+deb.sury.org+1

**Comment by z4yx** [comment]
php7已经删除了本项目依赖的mysqlnd扩展，请使用php 5.x版本

**Comment by xslingcn** [comment]
在problem页面出现
> failed to get dir
所有文件夹已经chown www-data

**Comment by z4yx** [comment]
是不是没有创建每道题的数据文件夹
